import { flattenCircuit } from "./flatten.js";
import { expression } from "./expression.js";
export function exportVerilog(circuit, data) {
  const m = flattenCircuit(circuit, data),
    lines = [
      `// Generated by Logic Forge. Scalar structural netlist.`,
      `module ${m.name}(${m.ports.map((p) => p.name).join(", ")});`,
      ...m.ports.map(
        (p) =>
          `${p.direction === "INPUT" ? "input" : "output"} wire ${p.name};`,
      ),
      ...m.nets.map((n) => "wire " + n + ";"),
    ];
  const ref = (p) => (p.inverse ? "~" + p.net : p.net);
  for (const [a, b] of m.assignments)
    lines.push(`assign ${a} = ${typeof b === "string" ? b : ref(b)};`);
  for (const g of m.gates) {
    const e = expression(g, "verilog");
    if (e !== null) {
      for (const p of Object.values(g.outputs))
        lines.push(`assign ${p.net} = ${p.inverse ? "~(" + e + ")" : e};`);
      continue;
    }
    const q = "q_" + g.name,
      ins = g.inputs,
      clk = ins.C || ins.CK || ins.CLK,
      d = ins.D;
    if (!clk || !d) throw Error("D/클록 핀이 없는 순차 소자: " + g.type);
    if (clk.inverse) throw Error("반전 클록에 별도 인버터를 배치하세요.");
    const ar = ins.CLR,
      as = ins.PRE,
      reset = ar || ins.R,
      set = as || ins.S,
      enable = ins.CE || ins.EN;
    lines.push(
      `reg ${q} = 1'b0;`,
      `always @(posedge ${ref(clk)}${ar ? " or posedge " + ref(ar) : ""}${as ? " or posedge " + ref(as) : ""}) begin`,
    );
    if (reset) lines.push(`  if (${ref(reset)}) ${q} <= 1'b0;`);
    if (set)
      lines.push(`  ${reset ? "else " : ""}if (${ref(set)}) ${q} <= 1'b1;`);
    lines.push(
      `  ${reset || set ? "else " : ""}${enable ? "if (" + ref(enable) + ") " : ""}${q} <= ${ref(d)};`,
      "end",
    );
    for (const [n, p] of Object.entries(g.outputs))
      lines.push(
        `assign ${p.net} = ${p.inverse !== (n === "QB") ? "~" : ""}${q};`,
      );
  }
  lines.push("endmodule");
  return lines.join("\n") + "\n";
}
